param(
  [switch]$ProfilesOnly
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
  return Split-Path -Parent $PSScriptRoot
}

function Ensure-Chocolatey {
  if (Get-Command choco -ErrorAction SilentlyContinue) {
    return
  }

  Write-Host "Chocolatey is not installed. Installing Chocolatey..."
  Set-ExecutionPolicy Bypass -Scope Process -Force
  [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
  Invoke-Expression ((New-Object System.Net.WebClient).DownloadString("https://community.chocolatey.org/install.ps1"))
}

function Add-ChocolateyBinToPath {
  $chocoRoot = if ($env:ChocolateyInstall) {
    $env:ChocolateyInstall
  } else {
    "C:\ProgramData\chocolatey"
  }

  $chocoBin = Join-Path $chocoRoot "bin"
  if ((Test-Path -LiteralPath $chocoBin) -and ($env:Path -notlike "*$chocoBin*")) {
    $env:Path = "$chocoBin;$env:Path"
  }
}

function Get-MiseExecutable {
  $mise = Get-Command mise -ErrorAction SilentlyContinue
  if ($null -ne $mise) {
    return $mise.Source
  }

  $candidates = @()
  if ($env:ChocolateyInstall) {
    $candidates += (Join-Path $env:ChocolateyInstall "bin\mise.exe")
  }
  $candidates += "C:\ProgramData\chocolatey\bin\mise.exe"

  foreach ($candidate in $candidates | Select-Object -Unique) {
    if (Test-Path -LiteralPath $candidate) {
      return $candidate
    }
  }

  return $null
}

function Set-ManagedProfileContent {
  param(
    [string]$Path,
    [string]$Content,
    [string]$Marker
  )

  if ((Test-Path -LiteralPath $Path) -and (-not (Select-String -LiteralPath $Path -SimpleMatch $Marker -Quiet))) {
    Copy-Item -LiteralPath $Path -Destination ($Path + ".bak") -Force
  }

  Set-Content -LiteralPath $Path -Value $Content -Encoding utf8
}

function Ensure-PowerShellProfileBridges {
  $documentsRoot = [Environment]::GetFolderPath("MyDocuments")
  $profileDirectories = @("PowerShell", "WindowsPowerShell")
  $managedMarker = "Generated by ~/.config/windows/setup.ps1."

  $sharedProfileContent = @'
# Generated by ~/.config/windows/setup.ps1.
$dotfilesProfile = Join-Path $env:USERPROFILE ".config\powershell\profile.ps1"
if (Test-Path -LiteralPath $dotfilesProfile) {
  . $dotfilesProfile
}
'@

  $currentHostProfileContent = @'
# Generated by ~/.config/windows/setup.ps1.
$sharedProfile = Join-Path $PSScriptRoot "profile.ps1"
if (Test-Path -LiteralPath $sharedProfile) {
  . $sharedProfile
}
'@

  foreach ($profileDirectoryName in $profileDirectories) {
    $profileDirectory = Join-Path $documentsRoot $profileDirectoryName
    $sharedProfilePath = Join-Path $profileDirectory "profile.ps1"
    $currentHostProfilePath = Join-Path $profileDirectory "Microsoft.PowerShell_profile.ps1"

    New-Item -ItemType Directory -Path $profileDirectory -Force | Out-Null

    Set-ManagedProfileContent -Path $sharedProfilePath -Content $sharedProfileContent -Marker $managedMarker
    Set-ManagedProfileContent -Path $currentHostProfilePath -Content $currentHostProfileContent -Marker $managedMarker
  }
}

function Ensure-StandaloneCli {
  # Why: 自己更新ツールを mise [tools] に置くと更新経路が二重になるため、導入保証だけを担う。
  # 既導入の場合は更新せず、更新は claude update / codex update に任せる。
  if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    irm https://claude.ai/install.ps1 | iex
  }
  if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    throw "claude was not installed by the official installer."
  }

  if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
    irm https://chatgpt.com/codex/install.ps1 | iex
  }
  if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
    throw "codex was not installed by the official installer."
  }
}

$repoRoot = Get-RepoRoot
$installScript = Join-Path $PSScriptRoot "chocolatey\install.ps1"
$windowsMiseConfig = Join-Path $repoRoot "mise\entry.workstation-windows.toml"

Ensure-PowerShellProfileBridges

if ($ProfilesOnly) {
  Write-Host "PowerShell profile bridges refreshed."
  return
}

Ensure-Chocolatey
Add-ChocolateyBinToPath

if (-not (Test-Path -LiteralPath $installScript)) {
  throw "Chocolatey install script not found: $installScript"
}

& $installScript

$miseExe = Get-MiseExecutable
if ($null -eq $miseExe) {
  throw "mise executable was not found after Chocolatey install."
}

if (-not (Test-Path -LiteralPath $windowsMiseConfig)) {
  throw "Windows mise config not found: $windowsMiseConfig"
}

$env:MISE_CONFIG_FILE = $windowsMiseConfig
$miseEnvironmentTokens = @($env:MISE_ENV -split "," | Where-Object { $_ })
foreach ($requiredToken in @("shared", "workstation")) {
  if ($miseEnvironmentTokens -notcontains $requiredToken) {
    $miseEnvironmentTokens += $requiredToken
  }
}
$env:MISE_ENV = ($miseEnvironmentTokens -join ",")
Write-Host "Installing mise-managed Windows tools using $windowsMiseConfig..."
& $miseExe install
if ($LASTEXITCODE -ne 0) {
  throw "mise install failed."
}
Ensure-StandaloneCli

Write-Host "Windows bootstrap complete."
Write-Host "MISE_CONFIG_FILE=$windowsMiseConfig"
Write-Host "MISE_ENV=$env:MISE_ENV"
