tap "abue-ammar/tinycast", trusted: true
tap "daipeihust/tap"
tap "fujibee/agmsg", trusted: true
tap "olets/tap"
tap "perman/tap", "git@github.com:PERMAN/homebrew-tap.git"
tap "stablyai/orca"
tap "steipete/tap", trusted: true
tap "voicevox/voicevox", "https://github.com/VOICEVOX/homebrew-voicevox", trusted: true
brew "daipeihust/tap/im-select", trusted: true
brew "mysql", restart_service: :changed
brew "steipete/tap/peekaboo", trusted: true
brew "perman/tap/perman-aws-vault", trusted: true
brew "utf8proc", args: ["HEAD"]
brew "olets/tap/zsh-abbr@6", trusted: true
cask "1password"
cask "1password-cli"
cask "fujibee/agmsg/agmsg"
cask "android-studio"
cask "ankerwork"
cask "appcleaner"
cask "arc"
cask "asana"
cask "autodesk-fusion"
cask "aws-vpn-client"
cask "bitwarden"
cask "chatgpt"
cask "cleanshot"
cask "codexbar"
cask "coteditor"
cask "cursor"
cask "cyberduck"
cask "deckset"
cask "discord"
cask "figma"
cask "font-bebas-neue"
cask "font-biz-udgothic"
cask "font-biz-udmincho"
cask "font-biz-udpgothic"
cask "font-biz-udpmincho"
cask "font-inconsolata-nerd-font"
cask "font-noto-color-emoji"
cask "font-prompt"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-udev-gothic-nf"
cask "google-drive"
cask "google-japanese-ime"
cask "hhkb"
cask "insomnia"
cask "istat-menus"
cask "karabiner-elements"
cask "keka"
cask "linearmouse"
cask "lm-studio"
cask "mimestream"
cask "monitorcontrol"
cask "notion"
cask "notion-calendar"
cask "obsidian"
cask "ollama-app"
cask "openvpn-connect"
cask "stablyai/orca/orca", trusted: true
cask "postman"
cask "raycast"
cask "session-manager-plugin"
cask "slack"
cask "spotify"
cask "synology-drive"
cask "tableplus"
cask "thaw"
cask "the-unarchiver"
cask "abue-ammar/tinycast/tinycast", trusted: true
cask "tradingview"
cask "visual-studio-code"
cask "vivaldi"
cask "voicevox/voicevox/voicevox"
cask "vorssaint"
cask "wezterm@nightly"
cask "xbar"
cask "zoom-for-it-admins"
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "BetterSnapTool", id: 417375580
mas "CommentScreen", id: 1450950860
mas "DaisyDisk", id: 411643860
mas "Darkroom", id: 953286746
mas "Developer", id: 640199958
mas "Howler Timer", id: 428846772
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Reeder", id: 1529448980
mas "Reeder", id: 6475002485
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "asvetliakov.vscode-neovim"
vscode "bfrangi.vscode-nightingale-theme"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "donjayamanne.githistory"
vscode "drblury.protobuf-vsc"
vscode "dzannotti.vscode-babel-coloring"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.remotehub"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hediet.vscode-drawio"
vscode "ics.japanese-proofreading"
vscode "ilkka.google-java-format"
vscode "jebbs.plantuml"
vscode "mechatroner.rainbow-csv"
vscode "mohsen1.prettify-json"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "mylesmurphy.prettify-ts"
vscode "prisma.prisma"
vscode "qufiwefefwoyn.kanagawa"
vscode "randomfractalsinc.vscode-data-preview"
vscode "redhat.fabric8-analytics"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "shopify.ruby-lsp"
vscode "takumii.markdowntable"
vscode "tamasfe.even-better-toml"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-lombok"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "zxh404.vscode-proto3"
