[tools]
biome = "2.2.4"
fd = "latest"
go = "1.23.3"
node = "22.20.0"
prettier = "3.4.2"
stylua = "0.20.0"
shfmt = "3.10.0"
luajit = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:markdown-link-check" = "latest"

[settings]
env_file = '.env'
experimental = true
vfox = false
idiomatic_version_file_enable_tools = ["go"]
trusted_config_paths = ['/Users/t00114/src/github.com']

[env]
_.source = [".venv/bin/activate"]

[tasks.format]
description = "Format all files"
run = [
  "biome format --write .",
  "markdownlint-cli2 --fix '**/*.md'",
  'fd -e md -X prettier --write',
  'fd -e yml -e yaml -X prettier --write',
  "stylua .",
  "fd -e sh -X shfmt -w",
]

[tasks.lint]
description = "Check all formatting and linting (GitHub Actions compatible)"
run = [
  "biome check --formatter-enabled=true --linter-enabled=true .",
  "markdownlint-cli2 '**/*.md'",
  'fd -e md -X prettier --check',
  'fd -e yml -e yaml -X prettier --check',
  "stylua --check .",
  "fd -e sh -X shfmt -d",
  "luacheck . || [ $? -eq 1 ]",
]

[tasks."lint:links"]
description = "Check markdown links (slow, run separately when needed)"
run = "fd -e md -x markdown-link-check --config .markdown-link-check.json"

[tasks.update]
description = "Update all dependencies"
run = ["mise run update:submodules", "mise run update:brew"]

[tasks."update:submodules"]
description = "Update git submodules to latest (discards local changes)"
run = "git submodule foreach 'git reset --hard HEAD && git clean -fd' && git submodule update --remote"

[tasks."update:brew"]
description = "Update Homebrew packages"
run = "brew update && brew upgrade"

[tasks.ci]
description = "Run all CI checks locally (same as GitHub Actions)"
run = ["mise run lint", "mise run lint:links"]

[tasks."ci:install"]
description = "Install additional tools required for CI"
run = ["luarocks install --local luacheck"]
