[files]
extend-exclude = ["raycast/**", "op/config", "*.pub", "Brewfile"]

# [default]
# extend-ignore-identifiers-re = [
#     # *sigh* this just isn't worth the cost of fixing
#     "AttributeID.*Supress.*",
# ]

# [default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
# AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
loca = "loca"
overriden = "overriden"
fo = "fo"
daa = "daa"
ba = "ba"
caf = "caf"
