[files]
extend-exclude = [
  "node_modules/**",
  "gen/**",
  "dist/**",
  "raycast/**",
  "op/config",
  "*.pub",
  "Brewfile",
  "*env*",
  "AWSVPNClient/**",
  "db/sql/**",
  "internals/**",
  "tmux/plugins/**",
]

# [default]
# extend-ignore-identifiers-re = [
#     # *sigh* this just isn't worth the cost of fixing
#     "AttributeID.*Supress.*",
# ]

# [default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
# AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
loca = "loca"
overriden = "overriden"
regist = "regist"
reserv = "reserv"
iterm = "iterm"
sur = "sur"

ue = "ue"
fo = "fo"
daa = "daa"
ba = "ba"
caf = "caf"
aso = "aso"
Ot = "Ot"
AAS = "AAS"
LSO = "LSO"
NAM = "NAM"
SOM = "SOM"
THA = "THA"
TTO = "TTO"
myu = "myu"
ono = "ono"
typ = "typ"
ser = "ser"
Inofficial = "Inofficial"
