shell = "zsh"

[templates]
noop = ""

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["source"]

[plugins.ni-completion]
github = "snowsman/ni-completion"
use = [".ni.zsh"]
apply = ["noop"]

[plugins.eza]
github = "eza-community/eza"
use = ["completions/zsh/_eza"]
apply = ["noop"]

[plugins.bun]
local = "~/.bun/"
use = ["_bun"]
apply = ["noop"]

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"
apply = ["noop"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["noop"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["noop"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["noop"]
