export MISE_DATA_DIR=$HOME/.mise
export MISE_CACHE_DIR=$MISE_DATA_DIR/cache

if ! command -v mise >/dev/null 2>&1; then
  return
fi

# Optimized mise loading - immediate PATH setup, deferred completion
# Activate immediately for PATH priority, defer only completion
if (( $+functions[zsh-defer] )); then
  # Immediate activation for proper PATH ordering
  eval "$(mise activate zsh)"
  eval "$(mise hook-env -s zsh)"
  # Defer only completion for startup performance
  zsh-defer -t 3 eval "$(mise complete -s zsh)"
else
  # Fallback for immediate loading when zsh-defer unavailable
  eval "$(mise activate zsh)"
  eval "$(mise hook-env -s zsh)"
  eval "$(mise complete -s zsh)"
fi

### Do not edit. This was autogenerated by 'mise direnv' ###
use_mise() {
  direnv_load mise direnv exec
}
