[[plugins]]
repo = 'onsails/lspkind-nvim'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = '''
source ~/.config/nvim/plugins/cmp.lua
'''

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'

# [[plugins]]
# repo = 'L3MON4D3/LuaSnip'
# hook_add = '''
# source ~/.config/nvim/plugins/LuaSnip.rc.vim
# '''
