[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
source ~/.config/nvim/plugins/ddc.rc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'ddc.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'InsertEnter'
depends = ['vim-vsnip-integ', 'friendly-snippets']
hook_source = '''
source ~/.config/nvim/plugins/vsnip.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = '''
source ~/.config/nvim/plugins/denops-popup-preview.rc.vim
'''

# [[plugins]]
# repo = 'Shougo/pum.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/pum.rc.vim
# '''

# [[plugins]]
# repo = 'Shougo/ddu.vim'
# depends = 'ddc.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/ddu.rc.vim
# '''
