[[plugins]]
repo = 'wavded/vim-stylus.git'
on_ft = ['stylus']

[[plugins]]
repo = 'tpope/vim-rake'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'vito-c/jq.vim'
on_ft = ['jq']

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_add = '''
source ~/.config/nvim/plugins/nvim-autopairs.lua
'''

# javascript
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'javascript', 'javascript.jsx', 'jsx']

[[plugins]]
repo = 'hotoo/jsgf.vim'
on_ft = ['typescript', 'typescript.tsx', 'tsx']

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = ['javascript', 'javascript.jsx', 'jsx', 'typescript', 'typescript.tsx', 'tsx']
hook_add = '''
source ~/.config/nvim/plugins/nvim-ts-autotag.lua
'''

[[plugins]]
repo = 'MunifTanjim/prettier.nvim'
hook_add = '''
source ~/.config/nvim/plugins/prettier.lua
'''

# [[plugins]]
# repo = 'github/copilot.vim'
