[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Gdiffsplit', 'Ggrep', 'Gstatus', 'Gwrite', 'Gcommit']
hook_add = '''
source ~/.config/nvim/plugins/fugitive.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'
depends = 'vim-fugitive'

[[plugins]]
repo = 'vim-scripts/renamer.vim'
on_cmd = ['Rename']

[[plugins]]
repo = 'h1mesuke/vim-alignta.git'
on_cmd    = ['Align', 'Alignta']
hook_add = '''
source ~/.config/nvim/plugins/vim-alignta.rc.vim
'''

[[plugins]]
repo = 'vim-scripts/sudo.vim'
on_cmd = ['SudoWrite', 'SudoRead']
