[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-lsp-installer', 'ddc.vim']
hook_add = '''
source ~/.config/nvim/plugins/nvim-lsp.rc.vim
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'matsui54/ddc-nvim-lsp-doc'
depends = ['ddc.vim']
hook_source = '''
let g:ddc_nvim_lsp_doc_config = {
     \ 'documentation': {
     \   'enable': v:true,
     \   'border': 'single',
     \   'maxWidth': 60,
     \   'maxHeight': 30,
     \ },
     \ 'signature': {
     \   'maxHeight': 5,
     \ },
     \ }
 call ddc_nvim_lsp_doc#enable()
'''
