[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-lsp-installer', 'ddc.vim']
hook_add = '''
source ~/.config/nvim/plugins/nvim-lsp.rc.vim
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
# depends = ['ddc.vim']
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'ray-x/lsp_signature.nvim'
# depends = ['ddc.vim']
