[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-lsp-installer', 'ddc.vim']
hook_add = '''
source ~/.config/nvim/plugins/nvim-lsp.rc.vim
'''
