[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-lsp-installer', 'ddc.vim']
hook_add = '''
source ~/.config/nvim/plugins/nvim-lsp.rc.vim
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['nvim-lspconfig']
hook_add = '''
source ~/.config/nvim/plugins/null-ls.lua
'''

[[plugins]]
repo = 'ray-x/lsp_signature.nvim'
# depends = ['ddc.vim']
