[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
 repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'

[[plugins]]
repo = 'nishigori/increment-activator'
hook_add = '''
source ~/.config/nvim/plugins/increment-activator.rc.vim
'''

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'akinsho/bufferline.nvim'
depends = 'nvim-web-devicons'
hook_add = '''
source ~/.config/nvim/plugins/bufferline.rc.vim
'''
[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = '''
source ~/.config/nvim/plugins/nvim-colorizer.rc.vim
'''
