[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
 repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'
