[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
 repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
depends = 'context_filetype.vim'
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add ='''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'nishigori/increment-activator'
hook_add = '''
source ~/.config/nvim/plugins/increment-activator.rc.vim
'''

[[plugins]]
repo = 'tomarrell/vim-npr'
hook_add = '''
let g:vim_npr_file_names = ["", ".js", ".jsx", ".ts", ".tsx", ".css", "/index.js", "/index.tsx"]
'''
