[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
source ~/.config/nvim/plugins/nvim-treesitter.lua
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
depends = 'nvim-treesitter'
hook_add = '''
source ~/.config/nvim/plugins/nvim-autopairs.lua
'''

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
depends = 'nvim-treesitter'
hook_add = '''
source ~/.config/nvim/plugins/nvim-ts-autotag.lua
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/.config/nvim/plugins/lualine.lua
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
depends = 'onedark.vim'
hook_add = '''
source ~/.config/nvim/plugins/vim-indent-guides.rc.vim
'''

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
hook_add = '''
source ~/.config/nvim/plugins/rainbow_parentheses.rc.vim
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = '''
source ~/.config/nvim/plugins/gitsigns.lua
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = '''
source ~/.config/nvim/plugins/nvim-colorizer.lua
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
source ~/.config/nvim/plugins/telescope.lua
'''

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'InsertEnter'
depends = ['vim-vsnip-integ', 'friendly-snippets']
hook_source = '''
source ~/.config/nvim/plugins/vsnip.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

