vim.g.increment_activator_filetype_candidates = {
  _ = {
    { "info", "warning", "notice", "error", "success" },
    { "mini", "small", "medium", "large", "xlarge", "xxlarge" },
    { "static", "absolute", "relative", "fixed", "sticky" },
    { "height", "width" },
    { "left", "right", "top", "bottom" },
    { "true", "false" },
    { "enable", "disable" },
    { "enabled", "disabled" },
    { "should", "should_not" },
    { "be_file", "be_directory" },
    { "div", "span", "Box" },
    { "column", "row" },
    { "start", "end" },
    { "before", "after" },
    { "head", "tail" },
    { "get", "post" },
    { "margin", "padding" },
    { "primary", "secondary", "tertiary" },
    { "development", "staging", "production" },
    { "const", "let" },
    { "dark", "medium", "light" },
    { "sm", "md", "lg", "xl", "xxl" },
    {
      "50",
      "100",
      "200",
      "300",
      "400",
      "500",
      "600",
      "700",
      "800",
      "900",
      "950",
    },
    { "slate", "gray", "zinc", "neutral", "stone" },
    {
      "red",
      "orange",
      "amber",
      "yellow",
      "lime",
      "green",
      "emerald",
      "teal",
      "cyan",
      "sky",
      "blue",
      "indigo",
      "violet",
      "purple",
      "fuchsia",
      "pink",
      "rose",
    },
  },
  ruby = {
    { "if", "unless" },
    { "nil", "empty", "blank" },
    {
      "string",
      "text",
      "integer",
      "float",
      "datetime",
      "timestamp",
      "timestamp",
    },
  },
  javascript = { { "props", "state" } },
  typescript = {
    { "string", "number", "boolean", "null", "undefined", "unknown", "Error" },
    { "void", "never" },
  },
  ["git-rebase-todo"] = {
    { "pick", "reword", "edit", "squash", "fixup", "exec" },
  },
}
