Set_keymap("[git]", "<Nop>", {})
Set_keymap("<C-g>", "[git]", {})
Set_keymap("[git]b", ":Git blame<CR>")
Set_keymap("[git]d", ":DiffviewOpen<CR>")
Set_keymap("[git]h", ":DiffviewFileHistory<CR>")
Set_keymap("[git]H", ":DiffviewFileHistory %<CR>")
Set_keymap("[git]D", ":Gdiffsplit<CR>")
Set_keymap("[git]e", ":DiffviewFocusFiles<CR>")
Set_keymap("[git]r", ":DiffviewRefresh<CR>")
Set_keymap("[git]g", ":Ggrep<Space>")
Set_keymap("[git]s", ":Git status<CR>")
Set_keymap("[git]w", ":Gwrite<CR>")
Set_keymap("[git]x", ":DiffviewClose<CR>")
