local set_opts = { noremap = true }

vim.api.nvim_set_keymap("n", "[git]", "<Nop>", {})
vim.api.nvim_set_keymap("n", "<C-g>", "[git]", {})
vim.api.nvim_set_keymap("n", "[git]b", ":Git blame<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]d", ":DiffviewOpen<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]h", ":DiffviewFileHistory<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]H", ":DiffviewFileHistory %<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]D", ":Gdiffsplit<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]e", ":DiffviewFocusFiles<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]r", ":DiffviewRefresh<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]g", ":Ggrep<Space>", set_opts)
vim.api.nvim_set_keymap("n", "[git]s", ":Git status<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]w", ":Gwrite<CR>", set_opts)
vim.api.nvim_set_keymap("n", "[git]x", ":DiffviewClose<CR>", set_opts)
