export MISE_DATA_DIR=$HOME/.mise
export MISE_CACHE_DIR=$MISE_DATA_DIR/cache

# Load command
eval "$(mise activate zsh)"
eval "$(mise hook-env -s zsh)"
# eval "$(mise complete -s zsh)"

### Do not edit. This was autogenerated by 'mise direnv' ###
use_mise() {
  direnv_load mise direnv exec
}
