export RTX_DATA_DIR=$HOME/.rtx
export RTX_CACHE_DIR=$RTX_DATA_DIR/cache

# Load command
eval "$(rtx activate zsh)"
eval "$(rtx hook-env -s zsh)"
# eval "$(rtx complete -s zsh)"

### Do not edit. This was autogenerated by 'rtx direnv' ###
use_rtx() {
  direnv_load rtx direnv exec
}
