name: Lua Lint and Format

on:
  push:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - 'stylua.toml'
      - '.github/workflows/lua.yml'
  pull_request:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - 'stylua.toml'
      - '.github/workflows/lua.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Lua (LuaJIT)
        uses: leafo/gh-actions-lua@v10
        with:
          lua-version: 'luajit'

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacheck
        run: luarocks install --local luacheck

      - name: Add LuaRocks bin to PATH
        run: echo "${HOME}/.luarocks/bin" >> $GITHUB_PATH

      - name: Lint with luacheck
        run: luacheck .

      - name: Format check with stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
