name: Validate Nix Flake

on:
  push:
    paths:
      - ".github/workflows/validate.yml"
      - "flake.nix"
      - "flake.lock"
      - "nix/**"
      - "home.nix"
  pull_request:
    paths:
      - ".github/workflows/validate.yml"
      - "flake.nix"
      - "flake.lock"
      - "nix/**"
      - "home.nix"
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Nix flake check
        run: nix flake check

      - name: Build bundle
        run: nix build .#bundle
